#! /bin/sh

sxhkd &
spotifyd &
compton --use-damage --blur-background --vsync --glx-no-stencil --blur-kern 7x7box --unredir-if-possible &
polybar leorrbar &
feh --bg-fill /home/leorr/Wallpapers/reaching.jpg &
redshift &
unclutter -idle 1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
